=== opelsrx/xmltv/src/xml_files/second_xml.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="tvguide" type="tvguide_type"/>

	<xsd:complexType name="tvguide_type">
		<xsd:sequence>
			<xsd:element name="channel" type="channel_type" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="channel_type">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="logotype" type="xsd:string"/>
			<xsd:element name="show" type="show_type" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="show_type">
		<xsd:sequence>
			<xsd:element name="start" type="xsd:string"/>
			<xsd:element name="titel" type="xsd:string"/>
			<xsd:element name="desc" type="desc_type" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="desc_type">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="lang" type="xsd:string"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:schema>

=== opelsrx/xmltv/src/xml_files/second.xml
<?xml version="1.0" encoding="UTF-8"?>
<tvguide xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="second_xml.xsd">
   <channel>
      <name>1.bluemovie.de</name>
      <logotype>http://chanlogos.xmltv.se/1.bluemovie.de.png</logotype>
      <show>
         <start>01:00</start>
         <titel>Bedtime Stories - Teil 3</titel>
      </show>
      <show>
         <start>03:05</start>
         <titel>Die Frau meines Nachbarn</titel>
      </show>
      <show>
         <start>05:05</start>
         <titel>Freizügig im Fasching</titel>
      </show>
      <show>
         <start>06:25</start>
         <titel>Freizügig im Fasching</titel>
      </show>
      <show>
         <start>07:55</start>
         <titel>Die heimlichen Gelüste meiner Frau - Vol. 5</titel>
      </show>
      <show>
         <start>09:45</start>
         <titel>Mütter aus dem Wohnwagen</titel>
      </show>
      <show>
         <start>11:30</start>
         <titel>Love de Luxe</titel>
      </show>
      <show>
         <start>13:40</start>
         <titel>Bedtime Stories - Teil 3</titel>
      </show>
      <show>
         <start>15:45</start>
         <titel>Die Frau meines Nachbarn</titel>
      </show>
      <show>
         <start>17:45</start>
         <titel>Freizügig im Fasching</titel>
      </show>
      <show>
         <start>19:15</start>
         <titel>Die heimlichen Gelüste meiner Frau - Vol. 5</titel>
      </show>
      <show>
         <start>21:05</start>
         <titel>Mütter aus dem Wohnwagen</titel>
      </show>
      <show>
         <start>22:50</start>
         <titel>Love de Luxe</titel>
      </show>
   </channel>
   <channel>
      <name>animalplanet.se</name>
      <logotype>http://chanlogos.xmltv.se/animalplanet.se.png</logotype>
      <show>
         <start>01:08</start>
         <titel>Escape to Chimp Eden</titel>
         <desc lang="sv">Nicky blev utkastad från Johannesburg Zoo eftersom han vänslades för mycket med honorna. Vaknar kärleken till liv igen nu när hans gamla flamma flyttas till Chimp Eden?</desc>
      </show>
      <show>
         <start>01:35</start>
         <titel>Escape to Chimp Eden</titel>
         <desc lang="sv">Schimpansen Josephine rymmer från de vuxnas inhägnad och ger sig ut på äventyr. Kan hon fångas in igen?</desc>
      </show>
      <show>
         <start>02:00</start>
         <titel>Escape to Chimp Eden</titel>
         <desc lang="sv">Spänningarna mellan alfahannen Jao och nummer två Zac dras till sin spets. Jao är slug, men Zac är yngre och större. Vem går därifrån som segrare?</desc>
      </show>
      <show>
         <start>02:25</start>
         <titel>Escape to Chimp Eden</titel>
         <desc lang="sv">Tonys grå starr har gjort honom blind på ett öga. Kan hans syn återställas med en konstgjord lins? Om operationen misslyckas ser framtiden mörk ut för Tony.</desc>
      </show>
      <show>
         <start>02:50</start>
         <titel>Going Ape</titel>
         <desc lang="sv">Vi får se hur några av människoaporna från första säsongen klarat sig. Gorillaungen Shufai togs emot efter att ha blivit skjuten - hur gick det? Och kunde schimpansen Gah gå igen?</desc>
      </show>
      <show>
         <start>03:15</start>
         <titel>Going Ape</titel>
         <desc lang="sv">Två starka schimpanser rymmer och skötaren Felix är tvungen att söva dem med en pil innan de skadar någon. Rachel presenterar gorillaungen Pikin för några unga gorillor.</desc>
      </show>
      <show>
         <start>03:39</start>
         <titel>Going Ape</titel>
         <desc lang="sv">Veterinärteknikern Babs räddar en schimpans som illegalt hållits kedjad vid ett träd. Personalen på Mefous nationalpark hjälper den övergivna schimpansen Daniel att passa in.</desc>
      </show>
      <show>
         <start>04:02</start>
         <titel>Bad Dog</titel>
         <desc lang="sv">Ett par ägare undrar hur intelligent deras hund är, en bulldogg tror att allt tillhör henne och en katt stjäl från hela kvarteret.</desc>
      </show>
      <show>
         <start>04:49</start>
         <titel>Bad Dog</titel>
         <desc lang="sv">En hund älskar allt som har med glass att göra och en annan fastnar hela tiden i saker, medan en papegoja har fått för vana att rappa och svära.</desc>
      </show>
      <show>
         <start>05:36</start>
         <titel>Meet The Orangutans</titel>
         <desc lang="sv">Följ med och träffa föräldralösa orangutangungar som återhämtar sig på världens första orangutangreservat i Borneo innan de återvänder till det vilda.</desc>
      </show>
      <show>
         <start>06:00</start>
         <titel>Meet The Orangutans</titel>
         <desc lang="sv">När föräldralösa Gelison kom till Sepilok var han bara ett år gammal. Nu när han kommit tillrätta tänjer han på gränserna med sitt dåliga uppförande.</desc>
      </show>
      <show>
         <start>06:25</start>
         <titel>Whale Wars</titel>
         <desc lang="sv">Besättningen ombord på Sea Shepherd försöker reparera skrovskadan på Steve Irwin. Kommer de kunna fullfölja sina planerade attacker mot den japanska valflottan?</desc>
      </show>
      <show>
         <start>07:15</start>
         <titel>Wildest Middle East</titel>
         <desc lang="sv">Turkiet kryllar av kontraster, men naturen ställs inför extrema utmaningar. Berg, klimatförändringar och hotfulla kustlinjer är en del av problemet.</desc>
      </show>
      <show>
         <start>08:10</start>
         <titel>Wildest Middle East</titel>
         <desc lang="sv">Mellanösterns naturhistoria är häpnadsväckande, men knappt dokumenterad på film. Följ med och utforska djurlivet i snåriga skogar och karga öknar.</desc>
      </show>
      <show>
         <start>09:05</start>
         <titel>Wildest Middle East</titel>
         <desc lang="sv">Jordaniens naturliv står inför några av de största utmaningarna i världen. Allt levande i området styrs ständigt av den stekheta solen.</desc>
      </show>
      <show>
         <start>10:00</start>
         <titel>Wildest Middle East</titel>
         <desc lang="sv">Sanddynerna i norra Afrika kan se torra och karga ut, men där finns faktiskt ett rikt ekosystem med allt från Nilens krokodiler till hornhuggormar.</desc>
      </show>
      <show>
         <start>10:55</start>
         <titel>Wildest Middle East</titel>
         <desc lang="sv">Mellanösterns naturhistoria är häpnadsväckande, men knappt dokumenterad på film. Följ med och utforska djurlivet i snåriga skogar och karga öknar.</desc>
      </show>
      <show>
         <start>11:50</start>
         <titel>My Fat Pet</titel>
         <desc lang="sv">Travis måste hjälpa chihuahuan Chipa att gå ned i vikt och lära sig ignorera mat. Och så hjälper han en stor familj vars överviktiga gris riskerar att få allvarliga hälsoproblem.</desc>
      </show>
      <show>
         <start>12:45</start>
         <titel>The Bronx Zoo</titel>
         <desc lang="sv">En inblick i vardagslivet på Bronx Zoo, där vi får följa det dagliga arbetet som ger förstklassig omsorg åt djuren och dessutom undervisar allmänheten i djurliv och naturvård.</desc>
      </show>
      <show>
         <start>13:40</start>
         <titel>Life On Earth: A New Prehistory</titel>
         <desc lang="sv">Upptäck revolutionerande upptäckter i paleontologi när CGI blåser liv i nya tolkningar av djur vars utseende varit omdebatterat, och nyligen upptäckta livsformer.</desc>
      </show>
      <show>
         <start>14:35</start>
         <titel>Escape to Chimp Eden</titel>
         <desc lang="sv">Tonys grå starr har gjort honom blind på ett öga. Kan hans syn återställas med en konstgjord lins? Om operationen misslyckas ser framtiden mörk ut för Tony.</desc>
      </show>
      <show>
         <start>15:03</start>
         <titel>Going Ape</titel>
         <desc lang="sv">Vi får se hur några av människoaporna från första säsongen klarat sig. Gorillaungen Shufai togs emot efter att ha blivit skjuten - hur gick det? Och kunde schimpansen Gah gå igen?</desc>
      </show>
      <show>
         <start>15:30</start>
         <titel>Going Ape</titel>
         <desc lang="sv">Två starka schimpanser rymmer och skötaren Felix är tvungen att söva dem med en pil innan de skadar någon. Rachel presenterar gorillaungen Pikin för några unga gorillor.</desc>
      </show>
      <show>
         <start>15:58</start>
         <titel>Going Ape</titel>
         <desc lang="sv">Veterinärteknikern Babs räddar en schimpans som illegalt hållits kedjad vid ett träd. Personalen på Mefous nationalpark hjälper den övergivna schimpansen Daniel att passa in.</desc>
      </show>
      <show>
         <start>16:25</start>
         <titel>Escape to Chimp Eden</titel>
         <desc lang="sv">Eugene återvänder till Sudan för sin största räddningsinsats någonsin. Sju schimpanser väntar på att hämtas, men när en försvinner bryter paniken ut.</desc>
      </show>
      <show>
         <start>16:53</start>
         <titel>Escape to Chimp Eden</titel>
         <desc lang="sv">När Sudaninsatsen når sin höjdpunkt kämpar Eugene mot matbrist, byråkratiskt trassel och ett gäng vilda schimpansungar.</desc>
      </show>
      <show>
         <start>17:20</start>
         <titel>Into The Dragon's Lair</titel>
         <desc lang="sv">Kameramannen Didier Noirot och fotografen Roger Horrocks reser till papyrusgrottorna i Botswana för att komma närmare den fruktade nilkrokodilen än vad någon någonsin gjort förut.</desc>
      </show>
      <show>
         <start>18:15</start>
         <titel>Jaws Strikes Back</titel>
         <desc lang="sv">Greg Skomal och SharkCam-laget drar till Florida, hajattackernas centrum, för att undersöka varför jättehajar invaderar statens kust.</desc>
      </show>
      <show>
         <start>19:10</start>
         <titel>Saba And The Rhino's Secret</titel>
